# Generated by Django 5.0.6 on 2024-07-06 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
