# Generated by Django 5.0.6 on 2024-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_organisation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
