# Generated by Django 5.0.6 on 2024-07-07 21:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userId',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
