# Generated by Django 5.0.6 on 2024-07-07 22:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('orgId', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ManyToManyField(related_name='users', to='authentication.organization'),
        ),
    ]
